### ISSUE TITLE
Listener

### ISSUE THREAD

**Issue by Memery92** [techery/ProperRatingBar#1]
Great little library, just one suggestion/request.

Can you make the ProperRatingBar an argument of onRatePicked? This way work can be done on that specific ProperRatingBar without having to create a new listener for each object.

**Comment by Den-Rimus** [comment]
Changes for suggested improvement are now in code-review

**Comment by Memery92** [comment]
Excellent, thanks.

**Comment by Den-Rimus** [comment]
https://github.com/techery/ProperRatingBar/pull/2 was merged into master
