### ISSUE TITLE
Didn't succeed geting it with gradle

### ISSUE THREAD

**Issue by afaucogney** [techery/ProperRatingBar#3]
I just add this:

    compile 'com.github.techery:ProperRatingBar:113fdae1a9'

But it run long and then post:

    Error:(29, 13) Failed to resolve: com.github.techery:ProperRatingBar:113fdae1a9

**Comment by dimd13** [comment]
I add a Latest commit 527d371 num and it's work

**Comment by Den-Rimus** [comment]
Use this line: compile 'com.github.techery:ProperRatingBar:527d37188c' as @dimd13 suggested

I don't know where you tooks that `113fdae1a9` hash - there ain't a commit with that hash in this repository.

Closing this for now.

**Comment by afaucogney** [comment]
I just follow the instruction:

where xxxyyyzzzw = last 10 digits of desired commit to build

Is it the last or the first 10 digits ?

**Comment by dimd13** [comment]
Took at your README
compile 'com.github.techery:ProperRatingBar:xxxyyyzzzw' where xxxyyyzzzw = last 10 digits of desired commit to build.

LAST 10 digits!! not FIRST

**Comment by afaucogney** [comment]
this is what I have done:

![capture d ecran 2015-10-28 a 09 47 50](https://cloud.githubusercontent.com/assets/6554201/10783577/0cc848ca-7d59-11e5-9013-534b16c52783.png)

This is the first time that I sync lib with "commit version like" process.

**Comment by Den-Rimus** [comment]
I apologize for that typo. Of course, you should use *first* 10 letters. I've fixed that in README.md - thanks for pointing that out.

Sorry once again.

**Comment by afaucogney** [comment]
no problem ! it works now, and that's going to be interesting.
