### ISSUE TITLE
the property of step on rating are expected to be adding in the next time

### ISSUE THREAD

**Issue by ThinWonton** [techery/ProperRatingBar#7]
as title what  i says.
thank you for your help.

**Comment by Den-Rimus** [comment]
Do you mean ability to set some fractional number for rating, like 2.25?

**Comment by ThinWonton** [comment]
yes

**Comment by haidaraM** [comment]
It will be very nice to add step and allow float value for rating.

**Comment by Den-Rimus** [comment]
Duplicate of #16 as seems
