### ISSUE TITLE
Setting drawable tick programmatically

### ISSUE THREAD

**Issue by Ivolian** [techery/ProperRatingBar#9]
1. Create proper drawables with  Android-Iconics, such as:
private Drawable getSelectedDrawable() {
        return new IconicsDrawable(this)
                .icon(GoogleMaterial.Icon.gmd_star)
                .color(getResources().getColor(R.color.md_orange_300))
                .sizeDp(28);
 }
2. Set tickSelectedDrawable and tickSelectedDrawable.
3. Call redrawChildren.

**Comment by Den-Rimus** [comment]
Sorry for being unresponsive for a long time.

Yes, it would be awesome to have ability to set those Iconics drawables programmatically.

Related to #15

**Comment by Den-Rimus** [comment]
Renamed as issue is not about iconics but ability to programmatically set drawable.

**Comment by Den-Rimus** [comment]
Will close - further tracking is to be held in #15
